name: my-site
version: 0.1.0.0
build-type: Simple

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/asp-dsp#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: 
    - posts/Lab2
    - posts/Lab3
    - posts/Lab4
    - posts/Lab5
    - posts/Lab6
  dependencies:
    - lens
    - Chart
    - Chart-diagrams
    - colour
    - data-default-class
    - dsp
    - array

executables:
  site:
    main: site.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hakyll
      - pandoc
      - containers
      - my-site

# tests:
#   asp-dsp-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - asp-dsp
